[0m[[0m[31merror[0m] [0m[0m/home/ubuntu/workspace/Prova/Teste1/src/main/scala/Teste1.scala:117:31: Unit does not take parameters[0m
[0m[[0m[31merror[0m] [0m[0m          user1.criar_arquivo4()[0m
[0m[[0m[31merror[0m] [0m[0m                              ^[0m
[0m[[0m[31merror[0m] [0m[0mone error found[0m
